config/routes.rb
Rails.application.routes.draw do

  # =======================================
  #shopping cart
  # =======================================
  resources :themes, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy, :show]
  post "/hook" => "payments#hook"

  # =======================================
  # User Routes
  # =======================================
    # Devise
  devise_for :users, controllers: {sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', passwords: 'users/passwords'}
    # Account
  namespace :users, as: "user" do
    resources :accounts, only: [:index, :update]
  end

  resource :user, only: [:edit, :update]

    # User Sign Up related Documents
  get 'user/first_time_done', to: 'welcome#first_time_done', as: 'user_first_time_done'
  get "/facebook_signup_without_email_faq", to: "welcome#email"

  # =======================================
  # Projects
  # =======================================
  get '/projects/search' , to: "searches#project_search", as: 'project_search'
  resources :projects

  # =======================================
  # Themes
  # =======================================
  namespace :themes do
    resource :selectors, only: [:edit]
  end

  # =======================================
  # Static Pages
  # =======================================
  get "/terms_of_services", to: "static_pages#terms_and_conditions", as: "terms_of_services"
  get "/privacy", to: "static_pages#privacy", as: "privacy"
  get "/explained", to: "static_pages#explained", as: "explained"
  get "/contact_us", to: "static_pages#contact_us", as: "contact_us"
  # =======================================
  # System
  # =======================================
    # Initiate Subdomain Search
  constraints(Subdomain) do
    get '/',  to: "users/profiles#show", as: 'custom_root'
  end
    # Fall Back to Root Page
  root 'welcome#index'

    # Error
  get '/404', to: 'system/errors#error_404', as: 'error_404', via: :all
  get '/422', to: 'system/errors#error_422', as: 'error_422', via: :all
  get '/500', to: 'system/errors#error_500', as: 'error_500', via: :all
  get '/no_such_project', to: 'system/errors#error_no_such_project', as: 'error_no_such_project', via: :all
  get '/no_such_profile', to: 'system/errors#no_such_profile', as: 'no_such_profile', via: :all
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_many :user_tags
	has_many :users, through: :user_tags
	has_many :order_items

	default_scope { where(active: true) }
end

app/controllers/themes/selectors_controller.rb
class Themes::SelectorsController < ApplicationController
  include ApplicationHelper
  include Themes::SelectorsHelper
  protect_from_forgery
  before_action :authenticate_user!

  # def index
  # end

  # def show
  # end

  # def new
  # end

  # def create
  # end

  def edit
    save_back_url

    # Output for View Files
    @page_title = "Select Theme"
    @page_description = "Select the Makerz Profile Theme for your profile. Available after login."

    @themes = extract_user_themes
    @user_account = extract_user_account
    @back_url = back_url
  end

  # def update
  # end

  # def destroy
  # end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
	protect_from_forgery
	before_action :authenticate_user!

	def index
		save_back_url
		themes = Theme.all


		# Process output for views
		@page_title = "Shop for Theme"
		@page_description = "Shop New Themes for Your Makerz Profile. Accessible after Login."

		@js_custom_turbolink = { 'turbolinks-track' => true, "turbolinks-eval" => false }
		@user_themes = current_user.themes
		@order_item = current_order.order_items.new
		@themes = themes - @user_themes
		@back_url = back_url
	end
end

app/helpers/themes/selectors_helper.rb
module Themes::SelectorsHelper

	def extract_user_themes
		themes = current_user.themes.all
		themes = nil if themes.blank?
		themes
	end

	def extract_user_account
		@user_account = current_user.user_account
	end

end

app/helpers/themes_helper.rb
module ThemesHelper
	def set_theme_as_current_theme_for(params = {})
		user ||= params[:user]
		theme ||= params[:theme]
		return false if theme.nil? || user.nil?

		user.user_account[:current_theme] ||= theme.id
		user.save

		true
	end

	def populate_free_themes_for(params = {})
		user ||= params[:user]
		themes = params[:themes] || []
		return false if user.nil? || themes.blank?

		themes.each do |theme|
			user.user_themes.find_or_create_by(user_id: user.id, theme_id: theme.id)
		end
		true
	end

end

app/views/themes/_theme_row.erb
<% @themes.each do |theme| %>
	<div id='shapeshift-store-item-<%= theme.id %>' class="shapeshift-item product-item">
		<div class="row">

			<div class="col-xs-12">
				<img class="product-image" src="https://lh3.googleusercontent.com/_-GVaVdTHtZIn_HdhVq1_RUVG-HzXaSh1cY3Fu8udWW-=w1552-h970-no" alt=<%= theme.name %>></img>
			</div>

			<div class="col-xs-12">
				<div class="row">
					<div class="col-xs-12">
						<h2 class="product-font product-title"><%= theme.name %></h2>
					</div>

					<div class="col-xs-12">
						<h3 class="product-category">
							<span class="product-font product-sub-title">Suitable for: </span>
						</h3>
						<p class="product-font category-value"><%= theme.category %> food</p>
					</div>

					<div class="col-xs-12">
						<h3 class="product-description">
							<span class="product-font product-sub-title">Details: </span>
						</h3>
						<p class="product-font description-value">Description</p>
					</div>

					<div class="col-xs-12">
						<h3 class="product-price">
							<span class="product-font product-sub-title">Price: </span>
							<span class="product-font price-value"><%= number_to_currency theme.price %></span>
						</h3>
					</div>
				</div>
			</div>


			<div class="col-xs-12">
				<div class="row">
					<%= form_for @order_item, remote: true do |f| %>
						<div class="col-xs-12">
							<%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
							<%= f.hidden_field :theme_id, value: theme.id %>
						</div>
						<div class="col-xs-12">
							<%= f.submit "Add to Cart", class: "btn btn-block btn-mobile btn-primary" %>
						</div>
					<% end %>
				</div>
			</div>

		</div>
	</div>
<% end %>

app/views/themes/index.html.erb
<body class="bg-img-2 bg-cover-screen bg-repeat-y ">
	<%= render 'layouts/partials/common/body/header' %>
	<div class='content-wrapper'>

		<section id="theme-selector-index" class="section-1 pebble bg-pebble-white">
			<div class="row">
				<div class="col-xs-12">
					<h1 class="section-title">Shopping for Themes</h1>
				</div>
			</div>

			<% unless has_no_contents? @themes %>
				<div class="row">
					<div class="col-xs-12">
						<div id='shapeshift-list' class='shapeshift-list'>
							<%= render 'theme_row' %>
						</div>
					</div>
				</div>
			<% else %>
				<div class="row">
					<div class="col-xs-12">
						<h2 class="subtitle">Oops?!?! Out of Stocks!</h2>
						<p>No worries! More designs and publishing soon!</p>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<% unless has_no_contents? @themes %>
				<div class="row">
					<% unless session[:first_time] %>
						<div class="col-xs-12 col-sm-2">
							<%= link_to "Back", @back_url, class: "btn btn-block btn-mobile btn-warning" %>
						</div>
						<div class="col-xs-12 col-sm-4">
							<%= link_to "To Themes Selector", edit_themes_selectors_path, class: "btn btn-block btn-mobile btn-primary" %>
						</div>
						<div class="col-xs-12 col-sm-6">
							<%= link_to "Go to Cart", cart_path, class: "btn btn-block btn-mobile btn-success" %>
						</div>
					<% else %>
						<div class="col-xs-12">
							<%= link_to "Go to Cart", cart_path, class: "btn btn-block btn-mobile btn-success" %>
						</div>
					<% end %>
				</div>
			<% else %>
				<div class="row">
					<div class="col-sm-4"></div>
					<div class="col-xs-12 col-sm-4">
						<%= link_to "Back To Dashboard", user_accounts_path, class: "btn btn-block btn-mobile btn-warning" %>
					</div>
					<div class="col-sm-4"></div>
				</div>
			<% end %>

		</section>

		<%= render 'layouts/partials/common/body/alert_container' %>
		<div class='footer-spacing'></div>
	</div>
	<%= render 'layouts/partials/common/body/footer' %>
</body>