config/routes.rb
Rails.application.routes.draw do

  # =======================================
  #shopping cart
  # =======================================
  resources :themes, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy, :show]
  post "/hook" => "payments#hook"

  # =======================================
  # User Routes
  # =======================================
    # Devise
  devise_for :users, controllers: {sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', passwords: 'users/passwords'}
    # Account
  namespace :users, as: "user" do
    resources :accounts, only: [:index, :update]
  end

  resource :user, only: [:edit, :update]

    # User Sign Up related Documents
  get 'user/first_time_done', to: 'welcome#first_time_done', as: 'user_first_time_done'
  get "/facebook_signup_without_email_faq", to: "welcome#email"

  # =======================================
  # Projects
  # =======================================
  get '/projects/search' , to: "searches#project_search", as: 'project_search'
  resources :projects

  # =======================================
  # Themes
  # =======================================
  namespace :themes do
    resource :selectors, only: [:edit]
  end

  # =======================================
  # Static Pages
  # =======================================
  get "/terms_of_services", to: "static_pages#terms_and_conditions", as: "terms_of_services"
  get "/privacy", to: "static_pages#privacy", as: "privacy"
  get "/explained", to: "static_pages#explained", as: "explained"
  get "/contact_us", to: "static_pages#contact_us", as: "contact_us"
  # =======================================
  # System
  # =======================================
    # Initiate Subdomain Search
  constraints(Subdomain) do
    get '/',  to: "users/profiles#show", as: 'custom_root'
  end
    # Fall Back to Root Page
  root 'welcome#index'

    # Error
  get '/404', to: 'system/errors#error_404', as: 'error_404', via: :all
  get '/422', to: 'system/errors#error_422', as: 'error_422', via: :all
  get '/500', to: 'system/errors#error_500', as: 'error_500', via: :all
  get '/no_such_project', to: 'system/errors#error_no_such_project', as: 'error_no_such_project', via: :all
  get '/no_such_profile', to: 'system/errors#no_such_profile', as: 'no_such_profile', via: :all
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :project_tags
	has_many :tags, through: :project_tags
	has_many :photos
	has_many :videos

	validates :title, presence: true, :uniqueness => { :scope => :user_id, message: "You have an existing project with the same name" }
	validates :motivation, presence: { message: "Motivation can't be empty. Let us know more about your project. Please key in some" }
	validates :description, presence: { message: "Description can't be empty. Potential users search based on the description. Please key in some" }

	accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: proc { |attributes| attributes.all? {|k,v| v.blank? } }
	accepts_nested_attributes_for :videos, allow_destroy: true, reject_if: proc { |attributes| attributes.all? {|k,v| v.blank? } }

	filterrific(
		default_filter_params: { sorted_by: 'created_at_desc' },
		available_filters: [
			:sorted_by,
			:search_query,
			:with_tag_id,
			:with_created_at_gte
		]
	)

	self.per_page = 20

	scope :search_query, lambda { |query|
		return nil if query.blank?
		terms = query.downcase.split(/\s+/)
		terms = terms.map { |e|
			(e.gsub('*', '%') + '%').gsub(/%+/, '%')
		}
		num_or_conditions = 3
		where(
			terms.map {
				or_clauses = [
					"LOWER(title) LIKE ?",
					"LOWER(description) LIKE ?",
					"LOWER(additional) LIKE ?"
				].join(' OR ')
				"(#{ or_clauses })"
			}.join(' AND '),
			*terms.map { |e| p [e] * num_or_conditions }.flatten)
	}

	scope :sorted_by, lambda { |sort_option|
		direction = (sort_option =~ /desc$/) ? "DESC" : "ASC"

		case sort_option.to_s
		when /^created_at_/
			order(created_at: direction)
		when /^name_/
			order(title: direction)
		when /^tag_name_/
			includes(:tags).order("tags.name #{ direction }")
		else
			raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
		end
	}

	scope :with_created_at_gte, lambda { |ref_date|
		where('created_at >= ?', ref_date)
	}

	scope :with_tag_id, lambda { |tag_ids|
		temp = tag_ids.split(/\W+/)
		joins(:tags).select('projects.*').where(tags: { name: [*temp] }).group('projects.id')
	}

	def project_tags_object
		tags.pluck(:name).join(", ")
	end

	def self.options_for_sorted_by
		[
			['Name (a-z)', 'name_asc'],
			['Name (z-a)', 'name_desc'],
			['Registration date (newest first)', 'created_at_desc'],
			['Registration date (oldest first)', 'created_at_asc'],
			['Tag (a-z)', 'tag_name_asc'],
			['Tag (z-a)', 'tag_name_desc']
		]
	end

	def decorated_created_at
		created_at.to_date.to_s(:long)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	include ProjectsHelper
	protect_from_forgery
	before_action :authenticate_user!
	before_action :validate_project_existance, only: [:edit, :show, :update, :destroy]
	before_action :validate_owner, only: [:edit, :update, :destroy]
	# before_action :validate_user_confirmation

	def index
		# Process output for views
		@page_title = "Project List"
		@page_description = "This is Makerz.io Project List, Accessible after Login."

		@projects = current_user.projects || []
		@default_picture = default_img_path
	end

	def new
		save_back_url

		# Process output for views
		@page_title = "New Project"
		@page_description = "This is Makerz.io New Project Creation for User, Accessible after Login."

		@project = current_user.projects.new
		@project.photos.build
		@project.videos.build
		@back_url = back_url
	end

	def create
		tags = split_tags(params[:project][:project_tags_object])

		params[:project].delete(:project_tags_object)

		@project = current_user.projects.new(project_params)

		@project.tags = tags

		if @project.save
			redirect_to projects_url, :notice => "Your project has been created"
		else
			render :new
		end

	end

	def edit
		@project.photos.build if has_no_contents? @project.photos
		@project.videos.build if has_no_contents? @project.videos

		# Process output for views
		@page_title = "Edit Project"
		@page_description = "This is Makerz.io Edit Project Creation for User, Accessible after Login."
			# @project is already handled by :validate_project_existance
	end

	def update
		tags = split_tags(params[:project][:project_tags_object])

		params[:project].delete(:project_tags_object)

		@project.attributes =  project_params
		@project.tags = tags

		if @project.save
			redirect_to projects_url, notice: 'This project was successfully updated.'
		else
			render :edit
		end
	end

	def show
		@owner = @project.user.user_account

		# Process output for views
		@page_title = "#{ @owner.name } - #{ @project.title }"
		@page_description = "This is Makerz.io Edit Project Creation for User, Accessible after Login."
		@project_tags = @project.tags.all.map { |tag| tag.name }.sort
		@owner_tags = @project.user.tags.all.map { |tag| tag.name }
	end

	def destroy
		@project.destroy
		redirect_to projects_url, :notice => "Your project was successfully deleted"
	end

	private
		def split_tags(tag_string)
			tags_array = tag_string.downcase.split(",").map(&:strip).reject(&:empty?).uniq

			tags_array.map do |tag|
				if tag.strip =~ Tag::TAG_REGEX
					tag_string = tag.strip.gsub(/[^a-zA-Z0-9\-]/,"")
				else
					tag_string = tag.strip
				end
				Tag.find_or_create_by(name: tag_string) if tag_string != ""
			end


		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def project_params
			params.require(:project).permit(:user_id, :title, :motivation, :description, :additional, :method, :project_tags_object,
																			photos_attributes: [:id, :url], videos_attributes: [:id, :url])
		end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def validate_project_existance
		@project = Project.find_by(id: params[:id])
		redirect_to projects_url, :alert => "No such project." if @project.nil?
	end

	def validate_owner
		unless @project.user.id == current_user.id
			redirect_to projects_url, alert: "Seems like you aren't the owner of the project.\n Let us know if you found any bugs. =)"
		end
	end

	def validate_user_confirmation
		redirect_to user_accounts_path, alert: "I'm sorry you have to confirm your account email in order to use this feature." unless current_user.confirmation_token.nil?
	end
end

app/views/projects/_form.erb
<%= form_for @project, :html => {:multipart => true}, validate: true do |f| %>
	<div class="row">
		<div class="col-xs-12">
			<div class="form-group">
				<span>Let's Give a <strong>TITLE</strong>: <strong style="color: red;">*</strong></span>
				<%= f.text_field :title, autofocus: true, class:'form-control', placeholder: "E.g: Bravo's Backing Machine", required: true %>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span><strong>MOTIVATION</strong> for making it: <strong style="color: red;">*</strong></span>
				<%= f.text_field :motivation, autofocus: true, class:'form-control', placeholder: "E.g.: I created this mainly for plain fun and helping people do XYZ.", required: true %>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span>Any <strong>DESCRIPTION</strong> for your masterpiece? <strong style="color: red;">*</strong></span>
				<%= f.text_area :description, autofocus: true, class:'form-control', rows: 4, placeholder: "E.g.: Well, it started of using some scrap metal, creating the body frame ....", required: true %>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span><strong>METHODS</strong> of making?</span>
				<br>
				<p class="text-xs">*Leave blank if you don't wish to share.</p>
				<%= f.text_area :method, autofocus: true, class:'form-control', rows: 4, placeholder: "Tell us more about how it works!\nLeave it empty if you don't wish to share. ;-) " %>

			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span><strong>ADDITIONAL</strong>notes?</span>
				<%= f.text_area :additional, autofocus: true, class:'form-control', rows: 4, placeholder: "Anything left out from here?" %>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span>Any <strong>PHOTO</strong> link?</span>
				<%= f.fields_for :photos do |ff| %>
					<%= ff.url_field :url, autofocus: true, class:'form-control', placeholder: "E.g: http://phtozo.com/555" %>
				<% end %>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span>Any<strong>VIDEO</strong> embed link?</span>
				<%= f.fields_for :videos do |ff| %>
					<%= ff.text_field :url, autofocus: true, class:'form-control', placeholder: 'E.g: <iframe width="640" height="360" src="https://www.youtube.com/embed/0HsPzzWnFbo" frameborder="0" allowfullscreen></iframe>' %>
				<% end %>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				<span>Finally Let's give some <strong>MAKERZ TAGS</strong>:</span>
				<%= f.text_field :project_tags_object, autofocus: true, class:'form-control', placeholder: "E.g: food, electronics, 3d_printer", required: true %>
			</div>
		</div>
	</div>

	<div class="actions">
		<div class="row">
			<div class="col-xs-12 col-sm-4">
				<%= link_to "Project Dashboard", projects_path, class: "btn btn-block btn-mobile btn-warning" %>
			</div>
			<div class="col-xs-12 col-sm-8">
				<%= f.submit "Create / Update", class: "btn btn-block btn-mobile btn-create btn-success" %>
			</div>
		</div>
	</div>
<% end %>

app/views/projects/_form_model.erb
<div class="modal fade" id="modal-show-project-<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
	<div class="modal-content">
		<%= render 'form_model_showcase', project: project %>

		<div class="modal-footer">
			<div class='row'>
				<div class='col-xs-12'>
					<%= link_to 'Delete', project, method: :delete, class: 'btn btn-block btn-mobile btn-danger',
						data: { :confirm => "Are you sure you want to delete #{project.title}",
								:'confirm-button-text' => 'Yes',
								:'cancel-button-text' => 'No way',
								:'confirm-button-color' => '#66CD00 ',
								:'sweet-alert-type' => 'info'
							  }
					%>
				</div>
				<div class='col-xs-12'>
					<%= link_to 'Modify', edit_project_path(project.id), class: 'btn btn-block btn-mobile btn-warning' %>
				</div>
				<div class='col-xs-12'>
					<button type="button" class="btn btn-block btn-mobile btn-primary" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/projects/_form_model_showcase.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<% unless has_no_contents? project.title %>
		<h4 class="modal-title"><%= project.title %></h4>
	<% else %>
		<h4 class="modal-title">Untitled</h4>
	<% end %>
</div>

<div class="modal-body">
	<div class='row'>
		<% unless has_no_contents? project.photos.first %>
			<div class='col-xs-12'>
				<img class="project-item-img" src="<%= project.photos.first.url %>" alt="<%= project.title %>.img"></img>
				<hr>
			</div>
		<% end %>

		<div class='col-xs-12'>
			<h5 class='text-lg'> Motivation </h5>
			<% unless has_no_contents? project.motivation %>
				<p class='text-sm'><%= project.motivation %></p>
			<% else %>
				<p>-</p>
			<% end %>
			<hr>
		</div>

		<div class='col-xs-12'>
			<h5 class='text-lg'> Description </h5>
			<% unless has_no_contents? project.description %>
				<p class='text-sm'><%= project.description %></p>
			<% else %>
				<p>-</p>
			<% end %>
			<hr>
		</div>
	</div>

	<div class='row'>
		<div class='col-xs-12'>
			<h5 class='text-lg'> Method </h5>
			<% unless has_no_contents? project.method %>
				<p class='text-sm'><%= project.method %></p>
			<% else %>
				<p>-</p>
			<% end %>
			<hr>
		</div>

		<% unless has_no_contents? project.videos.first %>
			<div class='col-xs-12'>
				<h5 class='text-lg'> Media </h5>
				<div class="project-item-video-container">
						<iframe class="project-item-video-frame" src="<%= project.videos.first.url %>" frameborder="0" allowfullscreen></iframe>
				</div>
				<hr>
			</div>
		<% end %>

		<div class='col-xs-12'>
			<h5 class='text-lg'> Additional </h5>
			<% unless has_no_contents? project.additional %>
				<p class='text-sm'><%= project.additional %></p>
			<% else %>
				<p>-</p>
			<% end %>
			<hr>
		</div>


		<div class='col-xs-12'>
			<h5 class='text-lg'>Tags</h5>
			<% unless has_no_contents? project.tags %>
				<p class='text-sm'><%= project.tags.all.map{ |tag| tag.name }.join(', ')  %></p>
			<% else %>
				<p>-</p>
			<% end %>
			<hr>
		</div>
	</div>
</div>

app/views/projects/edit.html.erb
<body class="bg-img-2 bg-cover-screen bg-repeat-y ">
	<%= render 'layouts/partials/common/body/header' %>
	<div class='content-wrapper'>
		<section id="project-edit" class="section-1 pebble bg-pebble-white">

			<div class="row">
				<div class="col-xs-12">
					<h2 class="section-heading">Edit Project</h2>
				</div>
			</div>

			<% unless @project.nil? %>
				<%= render 'projects/form' %>
			<% end %>

		</section>

		<%= render 'layouts/partials/common/body/alert_container' %>
		<div class='footer-spacing'></div>
	</div>
	<%= render 'layouts/partials/common/body/footer' %>
</body>

app/views/projects/index.html.erb
<body class='bg-img-2 bg-cover-screen bg-repeat-y'>
	<%= render 'layouts/partials/common/body/header' %>
	<div class='content-wrapper'>
		<section id='project-index' class='section-1 bg-pebble-white pebble'>

			<div class='row'>
				<% unless @projects.empty? %>
					<div class='col-xs-12 col-sm-9'>
						<h1 class='section-title'>My Projects</h1>
					</div>
					<div class='col-xs-12 col-sm-3'>
						<%= link_to new_project_path, class: "btn btn-block btn-primary" do %>
							<span class="glyphicon glyphicon-plus"></span> New Project</a>
						<% end %>
					</div>
				<% else %>
					<div class='col-xs-12'>
						<h1 class='section-title'>My Projects</h1>
					</div>
				<% end %>
			</div>


			<div class='row'>
				<% unless @projects.empty? %>
					<div id='shapeshift-list' class='shapeshift-list'>
						<% @projects.each do |project| %>
							<div id='shapeshift-project-item-<%= project.id %>' class='shapeshift-item'>
								<%= render 'form_model', project: project %>
								<div onClick='projectPopup(<%= project.id %>)' class="project-item-pebble bg-color-dark-blue">
									<% unless has_no_contents? project.photos.first %>
										<img class="project-item-img" src="<%= project.photos.first.url %>" alt="<%= project.title %>.img"></img>
									<% else %>
										<img class="project-item-img" src="<%= @default_picture %>" alt="<%= project.title %>.img"></img>
									<% end %>
									<h5><%= project.title %></h5>
								</div>

							</div>
						<% end %>
					</div>
				<% else %>
					<div class='col-xs-12' style='text-align: center;'>
						<div class='row bg-warning text-warning'>
							<div class='col-xs-12'>
								<h2>Oh dear!</h2>
								<p class='text-sm'>We can't find any.</p>
							</div>
						</div>
						<div class='row'>
							<div class='col-xs-12'>
								<%= link_to new_project_path, class: "btn btn-block btn-mobile btn-primary" do %>
									<span class="glyphicon glyphicon-plus"></span> Add your first project?</a>
								<% end %>
							</div>
						</div>
					</div>
				<% end %>
				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-4">
				</div>
				<div class="col-sm-4">
					<%= link_to "Back to Dashboard", user_accounts_path, class: "btn btn-block btn-mobile btn-warning" %>
				</div>
				<div class="col-sm-4">
				</div>
			</div>
		</section>
		<%= render 'layouts/partials/common/body/alert_container' %>
		<div class="footer-spacing"></div>
	</div>
	<%= render 'layouts/partials/common/body/footer' %>
</body>

app/views/projects/new.html.erb
<body class="bg-img-2 bg-cover-screen bg-repeat-y ">
	<%= render 'layouts/partials/common/body/header' %>
	<div class='content-wrapper'>
		<section id="project-new" class="section-1 pebble bg-pebble-white">

			<div class="row">
				<div class="col-xs-12">
					<h2 class="section-heading">New Project</h2>
				</div>
			</div>

			<% unless @project.nil? %>
				<%= render 'projects/form' %>
			<% end %>

		</section>

		<%= render 'layouts/partials/common/body/alert_container' %>
		<div class='footer-spacing'></div>
	</div>
	<%= render 'layouts/partials/common/body/footer' %>
</body>

app/views/projects/show.html.erb
<body class="bg-img-2 bg-cover-screen bg-repeat-y ">
	<%= render 'layouts/partials/common/body/header' %>
	<div class="content-wrapper"></div>
		<section id="project-show" class="section-1 pebble bg-pebble-white">

			<div class="row">
				<div class="col-xs-12">
					<h1 class="section-title"><%= @project.title %></h1>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
					<% unless has_no_contents? @project.photos.first %>
							<img class="project-item-img" src='<%= @project.photos.first.url %>' alt="<%= @project.title %>.img"></img>
					<% end %>

					<div class="align-center">
						<% unless has_no_contents? @project_tags %>
							<div class="row">
								<div class="col-xs-12">
									<h5>
									<%= @project_tags[0][0].match(/a|e|i|o|u/).nil? ? "A" : "An" %>
									<% @project_tags.each_with_index do |tag, index| %>
										<a href="#"><%= tag %></a>
										<% case index %>
										<% when @project_tags.size - 2 %>
											and
										<% when @project_tags.size - 1 %>
										<% else %>
											,
										<% end %>
									<% end %>
									project. </h5>
								</div>
							</div>
						<% end %>
					</div>
				</div>
				<div class="col-xs-12">
					<div class="row">
						<div class="col-xs-4">
							<h5><b>Date Made:</b></h5>
						</div>
						<div class="col-xs-8">
							<p> <%= @project.created_at %> </p>
						</div>
					</div>
				</div>
				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<div class="row">
				<div class='col-xs-12'>
					<h2>Maker:</h2>
				</div>

				<div class="col-xs-12">
					<div class="row">
						<div class="col-xs-4">
							<h5><b>Name:</b></h5>
						</div>
						<div class="col-xs-8">
							<p> <%= @owner.name %> </p>
						</div>
					</div>

					<% unless has_no_contents? @owner_tags %>
						<div class="row">
							<div class="col-xs-4">
								<h5><b>Maker of:</b></h5>
							</div>
							<div class="col-xs-8">
								<h5>
									<% @owner_tags.each_with_index do |tag, index| %>
										<a href="#"><%= tag %></a>
										<% case index %>
										<% when @owner_tags.size - 1 %>
										<% else %>
											,
										<% end %>
									<% end %>
								</h5>
							</div>
						</div>
					<% end %>

					<div class="row">
						<div class="col-xs-4">
							<h5><b>Profile:</b></h5>
						</div>
						<div class="col-xs-8">
							<p> <%= @owner.summary %> </p>
						</div>
					</div>

					<div class="row">
						<div class="col-xs-4">
							<h5><b>Contact:</b></h5>
						</div>
						<div class="col-xs-8">
							<% unless @owner.facebook_link.empty? %>
								<a class="btn btn-social-icon btn-facebook" href="<%= @owner.facebook_link %>"><i class="fa fa-facebook"></i></a>
							<% end %>
							<% unless @owner.twitter_link.empty? %>
								<a class="btn btn-social-icon btn-twitter" href="<%= @owner.twitter_link %>"><i class="fa fa-twitter"></i></a>
							<% end %>
							<% unless @owner.linkedIn_link.empty? %>
								<a class="btn btn-social-icon btn-linkedin" href="<%= @owner.linkedIn_link %>"><i class="fa fa-linkedin"></i></a>
							<% end %>
							<% unless @owner.google_plus_link.empty? %>
								<a class="btn btn-social-icon btn-google" href="<%= @owner.google_plus_link %>"><i class="fa fa-google-plus"></i></a>
							<% end %>
						</div>
					</div>
				</div>

				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<div class="row">
				<div class='col-xs-12 col-sm-4'>
					<h2>Inspiration</h2>
				</div>

				<div class="col-xs-12 col-sm-8">
					<p><%= @project.motivation %> </p>
				</div>

				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<% unless has_no_contents? @project.videos.first %>
				<div class="row">
					<div class='col-xs-12 col-sm-4'>
						<h2>Media</h2>
					</div>
					<div class="col-xs-12 col-sm-8">
						<div class="project-item-video-container">
								<iframe class="project-item-video-frame" src="<%= @project.videos.first.url %>" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
					<div class="col-xs-12">
						<hr>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class='col-xs-12 col-sm-4'>
					<h2>The Story</h2>
				</div>

				<div class="col-xs-12 col-sm-8">
					<p> <%= @project.description %> </p>
				</div>

				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<% unless @project.method.nil? %>
				<div class="row">
					<div class='col-xs-12 col-sm-4'>
						<h2>How it Works</h2>
					</div>

					<div class="col-xs-12 col-sm-8">
						<p> <%= @project.method %> </p>
					</div>

					<div class="col-xs-12">
						<hr>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class='col-xs-12 col-sm-4'>
					<h2>Remarks</h2>
				</div>

				<div class="col-xs-12 col-sm-8">
					<p> <%= @project.additional %> </p>
				</div>

				<div class="col-xs-12">
					<hr>
				</div>
			</div>

			<div class="row">
				<% unless current_user %>
					<div class="col-xs-12">
						<%= link_to "User Dashboard", projects_path, class: "btn btn-block btn-mobile btn-warning" %>
					</div>
				<% else %>
					<div class="col-xs-12">
						<%= link_to "Sign Up to Know More", projects_path, class: "btn btn-block btn-mobile btn-default" %>
					</div>
				<% end %>
			</div>

		</section>
		<%= render 'layouts/partials/common/body/alert_container' %>
		<div class="footer-spacing"></div>
	</div>
	<%= render 'layouts/partials/common/body/footer' %>
</body>