config/routes.rb
Rails.application.routes.draw do

  # =======================================
  #shopping cart
  # =======================================
  resources :themes, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy, :show]
  post "/hook" => "payments#hook"

  # =======================================
  # User Routes
  # =======================================
    # Devise
  devise_for :users, controllers: {sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', passwords: 'users/passwords'}
    # Account
  namespace :users, as: "user" do
    resources :accounts, only: [:index, :update]
  end

  resource :user, only: [:edit, :update]

    # User Sign Up related Documents
  get 'user/first_time_done', to: 'welcome#first_time_done', as: 'user_first_time_done'
  get "/facebook_signup_without_email_faq", to: "welcome#email"

  # =======================================
  # Projects
  # =======================================
  get '/projects/search' , to: "searches#project_search", as: 'project_search'
  resources :projects

  # =======================================
  # Themes
  # =======================================
  namespace :themes do
    resource :selectors, only: [:edit]
  end

  # =======================================
  # Static Pages
  # =======================================
  get "/terms_of_services", to: "static_pages#terms_and_conditions", as: "terms_of_services"
  get "/privacy", to: "static_pages#privacy", as: "privacy"
  get "/explained", to: "static_pages#explained", as: "explained"
  get "/contact_us", to: "static_pages#contact_us", as: "contact_us"
  # =======================================
  # System
  # =======================================
    # Initiate Subdomain Search
  constraints(Subdomain) do
    get '/',  to: "users/profiles#show", as: 'custom_root'
  end
    # Fall Back to Root Page
  root 'welcome#index'

    # Error
  get '/404', to: 'system/errors#error_404', as: 'error_404', via: :all
  get '/422', to: 'system/errors#error_422', as: 'error_422', via: :all
  get '/500', to: 'system/errors#error_500', as: 'error_500', via: :all
  get '/no_such_project', to: 'system/errors#error_no_such_project', as: 'error_no_such_project', via: :all
  get '/no_such_profile', to: 'system/errors#no_such_profile', as: 'no_such_profile', via: :all
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	protect_from_forgery

  def project_search
  	@filterrific = initialize_filterrific(
      Project,
      params[:filterrific], select_options: {
        sorted_by: Project.options_for_sorted_by,
        with_tag_id: Tag.options_for_select
      }
    ) or return

    # Process output for views
    @page_title = "Search Project"
    @page_description = "Search any project through Makerz tag or title."
    @projects = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_list.erb
<%# app/views/projects/_list.html.erb %>
<div id="filterrific_results">

	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<%= page_entries_info projects %>
		</div>
		<div class="col-xs-12 col-sm-6">
			<%= render_filterrific_spinner %>
		</div>
	</div>

	<div class="row">
		<div class="table-responsive">
			<table class="table table-hover">
				<tr>
					<th>Title</th>
					<th>Description</th>
					<th>Additional</th>
					<th>Tags</th>
					<th>Registered at</th>
					<th>Maker Name</th>
				</tr>
				<% projects.each do |project| %>
					<tr>
						<td><%= link_to(project.title, project_path(project)) %></td>
						<td><%= project.description %></td>
						<td><%= project.additional %></td>
						<td><% project.tags.each do |tag| %>
								<%= tag.name %> ,
								<% end %></td>
						<td><%= project.decorated_created_at %></td>
						<td><%= link_to project.user.user_account.name, root_url(:subdomain => project.user.user_account.subdomain) %>
							</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>

</div>

<%= will_paginate projects, renderer: BootstrapPagination::Rails %>

app/views/searches/project_search.html.erb
<body class='bg-img-2 bg-cover-screen bg-repeat-y'>
	<%= render 'layouts/partials/common/body/header' %>
	<div class='content-wrapper'>
		<section id='project-index' class='section-1 bg-pebble-white pebble'>
			<div class="row">
				<div class="col-xs-12">
					<h1 class="section-title">Search Project By:</h1>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-4">
					<%= form_for_filterrific @filterrific, url: project_search_path, remote: true do |f| %>
						<div class="row">
							<div class="col-xs-12">

							</div>

							<div class="col-xs-12">
								<div class="form-group">
									<h2 class="section-subtitle">Title:</h2>
									<%= f.text_field(:search_query, class: 'form-control filterrific-periodically-observed') %>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-xs-12">
								<div class="form-group">
									<h2 class="section-subtitle">Tag:</h2>
									<%= f.text_field(:with_tag_id, class: 'form-control filterrific-periodically-observed') %>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-xs-12">
								<div class="form-group">
									<h2 class="section-subtitle">Sorted by</h2>
									<%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], {}, {class: "form-control"}) %>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-xs-12">
								<div class="form-group">
									<div class="row">
										<div class="col-xs-12 col-sm-6">
											<%= link_to 'New Search', reset_filterrific_url, class: "btn btn-block btn-mobile btn-warning"  %>
										</div>
										<div class="col-xs-12 col-sm-6">
											<%= f.submit "Show projects", class: "btn btn-block btn-mobile btn-success" %>
										</div>
									</div>
								</div>
							</div>
						</div>

					<% end %>
				</div>

				<div class="col-xs-12 col-sm-offset-1 col-sm-7">
					<div id="results">
						<%= render(partial: 'list', locals: { projects: @projects }) %>
					</div>
				</div>
			</div>

<script type="text/javascript">
	$('.js-datepicker').datepicker();
</script>

		</section>
		<%= render 'layouts/partials/common/body/alert_container' %>
		<div class="footer-spacing"></div>
	</div>
	<%= render 'layouts/partials/common/body/footer' %>
</body>

app/views/searches/project_search.js.erb
<% js = escape_javascript(
  render(
    :partial => 'searches/list',
    :locals => { :projects => @projects }
  )
) %>
$("#results").html("<%= js %>");