config/routes.rb
Rails.application.routes.draw do

  # =======================================
  #shopping cart
  # =======================================
  resources :themes, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy, :show]
  post "/hook" => "payments#hook"

  # =======================================
  # User Routes
  # =======================================
    # Devise
  devise_for :users, controllers: {sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', passwords: 'users/passwords'}
    # Account
  namespace :users, as: "user" do
    resources :accounts, only: [:index, :update]
  end

  resource :user, only: [:edit, :update]

    # User Sign Up related Documents
  get 'user/first_time_done', to: 'welcome#first_time_done', as: 'user_first_time_done'
  get "/facebook_signup_without_email_faq", to: "welcome#email"

  # =======================================
  # Projects
  # =======================================
  get '/projects/search' , to: "searches#project_search", as: 'project_search'
  resources :projects

  # =======================================
  # Themes
  # =======================================
  namespace :themes do
    resource :selectors, only: [:edit]
  end

  # =======================================
  # Static Pages
  # =======================================
  get "/terms_of_services", to: "static_pages#terms_and_conditions", as: "terms_of_services"
  get "/privacy", to: "static_pages#privacy", as: "privacy"
  get "/explained", to: "static_pages#explained", as: "explained"
  get "/contact_us", to: "static_pages#contact_us", as: "contact_us"
  # =======================================
  # System
  # =======================================
    # Initiate Subdomain Search
  constraints(Subdomain) do
    get '/',  to: "users/profiles#show", as: 'custom_root'
  end
    # Fall Back to Root Page
  root 'welcome#index'

    # Error
  get '/404', to: 'system/errors#error_404', as: 'error_404', via: :all
  get '/422', to: 'system/errors#error_422', as: 'error_422', via: :all
  get '/500', to: 'system/errors#error_500', as: 'error_500', via: :all
  get '/no_such_project', to: 'system/errors#error_no_such_project', as: 'error_no_such_project', via: :all
  get '/no_such_profile', to: 'system/errors#no_such_profile', as: 'no_such_profile', via: :all
end

app/views/layouts/partials/common/body/_alert_container.erb
<%= devise_error_messages! %>
<% if notice %>
	<div id='flash-message' data-msg="<%= notice %>" data-notice="success"></div>
<% end %>
<% if alert %>
	<div id='flash-message' data-msg="<%= alert %>" data-notice="warning"></div>
<% end %>

app/views/layouts/partials/common/body/_analytics.erb
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-66721735-1', 'auto');
	ga('send', 'pageview');
</script>

app/views/layouts/partials/common/body/_cart_text.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-success" %>

app/views/layouts/partials/common/body/_footer.erb
<footer id='footer' class='footer'>
	<div class="row">
		<div class="container-fluid">
			<div class="col-lg-12 text-center">

				<ul class="list-inline">
					<li><%= link_to 'Privacy Policy', privacy_path %></li>
					<li><%= link_to 'Terms of Service', terms_of_services_path %></li>
					<li><%= link_to 'Contact Us', contact_us_path %></li>
				</ul>
				<p class="copyright text-sm text-muted">
					&copy; 2015. All rights reserved.
				</p>
			</div>
		</div>
	</div>
	<%= render 'layouts/partials/common/body/analytics' %>
</footer>

app/views/layouts/partials/common/body/_header.erb
<header class="header">
	<!--[if lt IE 7]>
		<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
	<![endif]-->
	<%= render 'layouts/partials/common/body/nav_bar' %>
	<div class="turnDeviceNotification"></div>
</header>

app/views/layouts/partials/common/body/_nav_bar.erb
<!-- Navigation & Logo-->
<nav class='navbar navbar-classic navbar-fixed-top'>
	<div class='container-fluid'>
		<div class='navbar-header'>
			<%= link_to "http://makerz.io", class: 'navbar-brand' do %>
				<img class="nav-bar-logo" src="https://docs.google.com/drawings/d/1lh8KqN9wJUkqFyZfmccqtlE1rZ7NeD_V3H9vFkPcAQM/pub?w=1892&amp;h=532" alt="Makerz.io"></img>
			<% end %>
			<button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
				<span class='sr-only'>Toggle navigation</span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
			</button>
		</div>
		<div id='navbar' class='navbar-collapse collapse'>
			<ul class='nav navbar-nav navbar-right'>
				<% if current_user  %>
					<li><%#= link_to 'Theme store', themes_path %></li>
					<li class="cart-text" ><%#= render 'layouts/partials/common/body/cart_text' %></li>
					<li><%= link_to 'Dashboard', "http://makerz.io" %></li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to 'Edit profile', edit_user_registration_path  %></li>
							<% if current_user.provider.nil?  %>
								<li><%= link_to 'Edit password', edit_user_path  %></li>
							<% end %>
							<li class="divider"></li>
							<li><%= link_to 'Logout', destroy_user_session_path  %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success' %></li>
					<li><%= link_to 'Login', new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>